arch = [
  "accountsservice",
  "acpi",
  "alsa-firmware",
  "alsa-plugins",
  "alsa-utils",
  "arandr",
  "archlinux-xdg-menu",
  "aspell",
  "awesome-terminal-fonts",
  "b43-fwcutter",
  "base",
  "base-devel",
  "bash-completion",
  "bind",
  "bluez",
  "bluez-utils",
  "brave-bin",
  "btrfs-progs",
  "cantarell-fonts",
  "cryptsetup",
  "cups",
  "cups-browsed",
  "cups-filters",
  "cups-pdf",
  "device-mapper",
  "dex",
  "diffutils",
  "dmenu",
  "dmidecode",
  "dmraid",
  "dnsmasq",
  "dosfstools",
  "downgrade",
  "dracut",
  "duf",
  "dunst",
  "e2fsprogs",
  "efibootmgr",
  "efitools",
  "ethtool",
  "exfatprogs",
  "f2fs-tools",
  "feh",
  "ffmpegthumbnailer",
  "firefox",
  "firewalld",
  "foomatic-db",
  "foomatic-db-engine",
  "foomatic-db-gutenprint-ppds",
  "foomatic-db-nonfree",
  "foomatic-db-nonfree-ppds",
  "foomatic-db-ppds",
  "galculator",
  "ghostscript",
  "git",
  "glances",
  "gnome-keyring",
  "gsfonts",
  "gst-libav",
  "gst-plugin-pipewire",
  "gst-plugins-bad",
  "gst-plugins-ugly",
  "gutenprint",
  "gvfs",
  "gvfs-afc",
  "gvfs-gphoto2",
  "gvfs-mtp",
  "gvfs-nfs",
  "gvfs-smb",
  "haveged",
  "hdparm",
  "hplip",
  "hwdetect",
  "hwinfo",
  "i3-wm",
  "i3blocks",
  "i3lock",
  "i3status",
  "inetutils",
  "intel-ucode",
  "inxi",
  "iptables-nft",
  "iwd",
  "jfsutils",
  "jq",
  "kernel-install-for-dracut",
  "less",
  "libdvdcss",
  "libgsf",
  "libopenraw",
  "libwnck3",
  "lightdm",
  "lightdm-slick-greeter",
  "linux",
  "linux-firmware",
  "linux-headers",
  "linux-lts",
  "linux-lts-headers",
  "logrotate",
  "lsb-release",
  "lsscsi",
  "lvm2",
  "man-db",
  "man-pages",
  "mdadm",
  "meld",
  "mesa-utils",
  "modemmanager",
  "mpv",
  "mtools",
  "nano",
  "nano-syntax-highlighting",
  "netctl",
  "network-manager-applet",
  "networkmanager",
  "networkmanager-openconnect",
  "networkmanager-openvpn",
  "nfs-utils",
  "nilfs-utils",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "noto-fonts-extra",
  "nss-mdns",
  "ntfs-3g",
  "ntp",
  "numlockx",
  "nwg-look",
  "openssh",
  "pacman-contrib",
  "pavucontrol",
  "perl",
  "picom",
  "pipewire-alsa",
  "pipewire-jack",
  "pipewire-pulse",
  "pkgfile",
  "playerctl",
  "plocate",
  "polkit-gnome",
  "poppler-glib",
  "power-profiles-daemon",
  "pv",
  "python",
  "python-capng",
  "python-defusedxml",
  "python-packaging",
  "python-pillow",
  "python-pyqt5",
  "python-reportlab",
  "rebuild-detector",
  "reflector",
  "reflector-simple",
  "reiserfsprogs",
  "ristretto",
  "rofi",
  "rsync",
  "rtkit",
  "s-nail",
  "sane",
  "scrot",
  "seahorse",
  "sg3_utils",
  "smartmontools",
  "sof-firmware",
  "splix",
  "sudo",
  "sysfsutils",
  "sysstat",
  "system-config-printer",
  "systemd-sysvcompat",
  "texinfo",
  "thunar",
  "thunar-archive-plugin",
  "thunar-volman",
  "tldr",
  "ttf-bitstream-vera",
  "ttf-dejavu",
  "ttf-liberation",
  "ttf-opensans",
  "tumbler",
  "unrar",
  "unzip",
  "upower",
  "usb_modeswitch",
  "usbutils",
  "vi",
  "welcome",
  "wget",
  "which",
  "wireplumber",
  "wpa_supplicant",
  "xarchiver",
  "xbindkeys",
  "xclip",
  "xdg-user-dirs",
  "xdg-user-dirs-gtk",
  "xdg-utils",
  "xed",
  "xf86-input-libinput",
  "xfce4-terminal",
  "xfsprogs",
  "xl2tpd",
  "xorg-server",
  "xorg-xbacklight",
  "xorg-xdpyinfo",
  "xorg-xinit",
  "xorg-xinput",
  "xorg-xkill",
  "xorg-xrandr",
  "xss-lock",
  "xterm",
  "yay",
  "zip",
  "zsh",
]
rustup = ["stable-x86_64-unknown-linux-gnu"]
