arch = [
  "arc-gtk-theme-eos",
  "endeavouros-branding",
  "endeavouros-keyring",
  "endeavouros-mirrorlist",
  "endeavouros-xfce4-terminal-colors",
  "eos-apps-info",
  "eos-hooks",
  "eos-lightdm-slick-theme",
  "eos-log-tool",
  "eos-packagelist",
  "eos-qogir-icons",
  "eos-quickstart",
  "eos-rankmirrors",
  "eos-settings-i3wm",
  "welcome",
]
