flatpak = [
  { package = "com.geekbench.Geekbench6", remote = "flathub" },
  { package = "md.obsidian.Obsidian", remote = "flathub" },
  { package = "com.ktechpit.whatsie", remote = "flathub" },
  { package = "net.scribus.Scribus", remote = "flathub" },
]
