arch = [
  "a52dec",
  "aom",
  "appstream",
  "bubblewrap",
  "c-ares",
  "cairomm-1.16",
  "chromaprint",
  "cifs-utils",
  "composefs",
  "cpio",
  "cracklib",
  "ding-libs",
  "dnssec-anchors",
  "dotnet-host",
  "dotnet-runtime-6.0",
  "double-conversion",
  "enchant",
  "exo",
  "faac",
  "faad2",
  "fd",
  "ffmpeg",
  "fftw",
  "fluidsynth",
  "fuse-common",
  "fuse2",
  "fuse3",
  "gcr",
  "gcr-4",
  "gd",
  "giflib",
  "glibmm-2.68",
  "glslang",
  "gobject-introspection-runtime",
  "gperftools",
  "graphene",
  "gsm",
  "gspell",
  "gssdp",
  "gssproxy",
  "gst-plugins-bad-libs",
  "gtk-layer-shell",
  "gtk4",
  "gtkmm-4.0",
  "gtksourceview4",
  "gupnp",
  "gupnp-igd",
  "harfbuzz-icu",
  "hidapi",
  "highway",
  "hyphen",
  "ijs",
  "imagemagick",
  "imath",
  "imlib2",
  "jbig2dec",
  "jemalloc",
  "l-smash",
  "ldb",
  "libaio",
  "libappindicator-gtk3",
  "libass",
  "libatasmart",
  "libavc1394",
  "libavif",
  "libavtp",
  "libblockdev",
  "libblockdev-crypto",
  "libblockdev-fs",
  "libblockdev-loop",
  "libblockdev-mdraid",
  "libblockdev-nvme",
  "libblockdev-part",
  "libblockdev-swap",
  "libbluray",
  "libbs2b",
  "libbsd",
  "libbytesize",
  "libcanberra",
  "libcdio",
  "libcdio-paranoia",
  "libconfig",
  "libcupsfilters",
  "libdbusmenu-glib",
  "libdbusmenu-gtk3",
  "libdc1394",
  "libdca",
  "libde265",
  "libdecor",
  "libdeflate",
  "libdovi",
  "libdv",
  "libdvdnav",
  "libdvdread",
  "libexif",
  "libgirepository",
  "libgme",
  "libgnomekbd",
  "libgphoto2",
  "libgtop",
  "libhandy",
  "libheif",
  "libidn",
  "libiec61883",
  "libieee1284",
  "libimagequant",
  "libimobiledevice",
  "libimobiledevice-glue",
  "libinih",
  "libinstpatch",
  "libjxl",
  "liblqr",
  "liblrdf",
  "libltc",
  "libmalcontent",
  "libmanette",
  "libmaxminddb",
  "libmbim",
  "libmd",
  "libmicrodns",
  "libmm-glib",
  "libmodplug",
  "libmpcdec",
  "libmpeg2",
  "libmtp",
  "libndp",
  "libnewt",
  "libnfs",
  "libnice",
  "libnm",
  "libnma",
  "libnma-common",
  "libnotify",
  "libnvme",
  "libopenmpt",
  "libpaper",
  "libpeas",
  "libpgm",
  "libpipeline",
  "libplacebo",
  "libplist",
  "libppd",
  "libpwquality",
  "libqmi",
  "libqrtr-glib",
  "libraqm",
  "libraw1394",
  "libsamplerate",
  "libsigc++-3.0",
  "libsixel",
  "libsodium",
  "libsoxr",
  "libsrtp",
  "libssh",
  "libteam",
  "libtheora",
  "libunibreak",
  "liburcu",
  "liburing",
  "libusbmuxd",
  "libvdpau",
  "libvpl",
  "libvpx",
  "libwbclient",
  "libwebp",
  "libx86emu",
  "libxfce4ui",
  "libxfce4util",
  "libxmlb",
  "libxpresent",
  "libxres",
  "libxslt",
  "libxss",
  "libyaml",
  "libyuv",
  "mailcap",
  "md4c",
  "mjpegtools",
  "mobile-broadband-provider-info",
  "mujs",
  "neofetch",
  "neon",
  "net-snmp",
  "nfsidmap",
  "nftables",
  "nm-connection-editor",
  "nspr",
  "nss",
  "oath-toolkit",
  "ocl-icd",
  "oniguruma",
  "openal",
  "openconnect",
  "opencore-amr",
  "openexr",
  "openh264",
  "openjpeg2",
  "openvpn",
  "ostree",
  "pacutils",
  "pahole",
  "pangomm-2.48",
  "parallel",
  "parted",
  "paru",
  "paru-debug",
  "pcre",
  "perl-alien-build",
  "perl-alien-libxml2",
  "perl-capture-tiny",
  "perl-clone",
  "perl-dbi",
  "perl-encode-locale",
  "perl-ffi-checklib",
  "perl-file-chdir",
  "perl-file-listing",
  "perl-file-which",
  "perl-html-parser",
  "perl-html-tagset",
  "perl-http-cookiejar",
  "perl-http-cookies",
  "perl-http-daemon",
  "perl-http-date",
  "perl-http-message",
  "perl-http-negotiate",
  "perl-io-html",
  "perl-libwww",
  "perl-lwp-mediatypes",
  "perl-net-http",
  "perl-path-tiny",
  "perl-try-tiny",
  "perl-uri",
  "perl-www-robotrules",
  "perl-xml-libxml",
  "perl-xml-namespacesupport",
  "perl-xml-parser",
  "perl-xml-sax",
  "perl-xml-sax-base",
  "perl-xml-writer",
  "pkcs11-helper",
  "poppler",
  "poppler-data",
  "portaudio",
  "ppp",
  "python-annotated-types",
  "python-argcomplete",
  "python-cairo",
  "python-chardet",
  "python-click",
  "python-colorama",
  "python-dbus",
  "python-distro",
  "python-gobject",
  "python-orjson",
  "python-platformdirs",
  "python-psutil",
  "python-pycups",
  "python-pydantic",
  "python-pydantic-core",
  "python-pyqt5-sip",
  "python-shtab",
  "python-termcolor",
  "python-typing_extensions",
  "python-userpath",
  "qpdf",
  "qrencode",
  "qt5-base",
  "qt5-translations",
  "raptor",
  "rav1e",
  "rpcbind",
  "rtmpdump",
  "rubberband",
  "sd",
  "sdl2-compat",
  "sdl3",
  "shaderc",
  "slang",
  "smbclient",
  "snappy",
  "sound-theme-freedesktop",
  "soundtouch",
  "spandsp",
  "speex",
  "speexdsp",
  "srt",
  "stoken",
  "svt-av1",
  "svt-hevc",
  "systemd-resolvconf",
  "talloc",
  "tcl",
  "tdb",
  "tevent",
  "thin-provisioning-tools",
  "tslib",
  "ttf-nerd-fonts-symbols",
  "ttf-nerd-fonts-symbols-common",
  "uchardet",
  "udisks2",
  "usbmuxd",
  "v4l-utils",
  "vapoursynth",
  "vid.stab",
  "vim",
  "vmaf",
  "volume_key",
  "vpnc",
  "vte-common",
  "vte3",
  "webkitgtk-6.0",
  "webp-pixbuf-loader",
  "wildmidi",
  "woff2",
  "x264",
  "x265",
  "xapp",
  "xcb-imdkit",
  "xcur2png",
  "xdg-dbus-proxy",
  "xdg-desktop-portal",
  "xfconf",
  "xmlsec",
  "xvidcore",
  "yyjson",
  "zbar",
  "zeromq",
  "zimg",
  "zvbi",
  "zxing-cpp",
]
