arch = [
    "adw-gtk-theme",
    "autorandr",
    "flatpak",
    "font-manager",
    "github-cli",
    "kitty",
    "metapac",
    "python-pipx",
    "ttf-meslo-nerd",
    "visual-studio-code-bin",
    "yazi"
]
