arch = [
  "adw-gtk-theme",
  "autorandr",
  "brightnessctl",
  "fastfetch",
  "flatpak",
  "font-manager",
  "github-cli",
  "kitty",
  "metapac",
  "pinta",
  "python-pipx",
  "ttf-meslo-nerd",
  "visual-studio-code-bin",
  "yazi",
]
