set autoindent
set clipboard="unnamedplus"
set expandtab
set fileencoding="utf-8"
set number
set relativenumber
set shiftwidth=2
set nospell
set splitbelow
set splitright
set noswapfile
set tabstop=2
set termguicolors
set nowrap
